from enum import Enum

class Stages(Enum):
    '''Enum representing legal stages. Stages >= 6 represent counterpicks'''
    battlefield = 1 #Battlefield
    bf = 1
    small_battlefield = 2 #Small Battlefield
    sbf = 2
    pokemon_stadium_2 = 3 #Pokemon Stadium 2
    ps2 = 3
    smashville = 4 #Smashville
    sv = 4
    town_and_city = 5 #Town and City
    tnc = 5
    final_destination = 6 #Final Destination
    fd = 6
    hollow_bastion = 7 #Hollow Bastion
    hb = 7
    kalos_pokemon_league = 8 #kalos Pokemon League
    kalos = 8

class Characters(Enum):
    total = -1
    random = 0
    mario = 1
    donkey_kong = 2
    dk = 2
    link = 3
    samus = 4
    dark_samus = 5
    dsamus = 5
    yoshi = 6
    kirby = 7
    fox = 8
    pikachu = 9
    luigi = 10
    ness = 11
    falcon = 12
    jigglypuff = 13
    peach = 14
    daisy = 15
    bowser = 16
    ice_climbers = 17
    icies = 17
    ics = 17
    sheik = 18
    zelda = 19
    dr_mario = 20
    pichu = 21
    falco = 22
    marth = 23
    lucina = 24
    young_link = 25
    yink = 25
    ganondorf = 26
    mewtwo = 27
    m2 = 27
    roy = 28
    chrom = 29
    mr_game_and_watch = 30
    gnw = 30
    meta_knight = 31
    mk = 31
    pit = 32
    dark_pit = 33
    dpit = 33
    zero_suit_samus = 34
    wario = 35
    snake = 36
    ike = 37
    pokemon_trainer = 38
    poketrainer = 38
    diddy_kong = 39
    diddy = 39
    lucas = 40
    sonic = 41
    king_dedede = 42
    dedede = 42
    olimar = 43
    lucario = 44
    rob = 45
    toon_link = 46
    tink = 46
    wolf = 47
    villager = 48
    mega_man = 49
    mm = 49
    wii_fit_trainer = 50
    wft = 50
    rosalina_and_luma = 51
    rosaluma = 51
    little_mac = 52
    mac = 52
    greninja = 53
    mii_brawler = 54
    brawler = 54
    mii_swordfighter = 55
    msf = 55
    mii_gunner = 56
    gunner = 56
    palutena = 57
    palu = 57
    pacman = 58
    robin = 59
    shulk = 60
    bowser_jr = 61
    bjr = 61
    duck_hunt = 62
    dh = 62
    ryu = 63
    ken = 64
    cloud = 65
    corrin = 66
    bayonetta = 67
    bayo = 67
    inkling = 68
    ridley = 69
    simon = 70
    richter = 71
    king_k_rool = 72
    krool = 72
    isabelle = 73
    incineroar = 74
    incin = 74
    piranha_plant = 75
    plant = 75
    joker = 76
    hero = 77
    banjo_and_kazooie = 78
    banjo = 78
    terry = 79
    byleth = 80
    min_min = 81
    steve = 82
    sephiroth = 83
    aegis = 84
    kazuya = 85
    sora = 86